# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chartWidget.ui'
#
# Created: Mon Jan  3 08:21:49 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_chartWidget(object):
    def setupUi(self, chartWidget):
        chartWidget.setObjectName("chartWidget")
        chartWidget.resize(1076, 1056)
        self.tabWidget = QtGui.QTabWidget(chartWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 870, 841, 161))
        self.tabWidget.setObjectName("tabWidget")
        self.chartControls = QtGui.QWidget()
        self.chartControls.setObjectName("chartControls")
        self.zoomIn = QtGui.QPushButton(self.chartControls)
        self.zoomIn.setGeometry(QtCore.QRect(30, 10, 110, 29))
        self.zoomIn.setObjectName("zoomIn")
        self.zoomOut = QtGui.QPushButton(self.chartControls)
        self.zoomOut.setGeometry(QtCore.QRect(30, 80, 110, 29))
        self.zoomOut.setObjectName("zoomOut")
        self.sma = QtGui.QPushButton(self.chartControls)
        self.sma.setGeometry(QtCore.QRect(370, 40, 110, 29))
        self.sma.setObjectName("sma")
        self.chartLength = QtGui.QLabel(self.chartControls)
        self.chartLength.setGeometry(QtCore.QRect(50, 50, 71, 19))
        self.chartLength.setObjectName("chartLength")
        self.candlestick = QtGui.QPushButton(self.chartControls)
        self.candlestick.setGeometry(QtCore.QRect(200, 40, 110, 29))
        self.candlestick.setObjectName("candlestick")
        self.ohlc = QtGui.QPushButton(self.chartControls)
        self.ohlc.setGeometry(QtCore.QRect(200, 80, 110, 29))
        self.ohlc.setObjectName("ohlc")
        self.line = QtGui.QFrame(self.chartControls)
        self.line.setGeometry(QtCore.QRect(160, 10, 16, 101))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtGui.QFrame(self.chartControls)
        self.line_2.setGeometry(QtCore.QRect(330, 10, 16, 101))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label = QtGui.QLabel(self.chartControls)
        self.label.setGeometry(QtCore.QRect(210, 10, 91, 19))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.chartControls)
        self.label_2.setGeometry(QtCore.QRect(370, 10, 161, 19))
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.chartControls, "")
        self.account = QtGui.QWidget()
        self.account.setObjectName("account")
        self.buy = QtGui.QPushButton(self.account)
        self.buy.setGeometry(QtCore.QRect(150, 60, 110, 29))
        self.buy.setObjectName("buy")
        self.sell = QtGui.QPushButton(self.account)
        self.sell.setGeometry(QtCore.QRect(30, 60, 110, 29))
        self.sell.setObjectName("sell")
        self.showBalance = QtGui.QLabel(self.account)
        self.showBalance.setGeometry(QtCore.QRect(160, 30, 101, 20))
        self.showBalance.setObjectName("showBalance")
        self.balanceLabel = QtGui.QLabel(self.account)
        self.balanceLabel.setGeometry(QtCore.QRect(50, 30, 71, 19))
        self.balanceLabel.setObjectName("balanceLabel")
        self.tabWidget.addTab(self.account, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.symbolEntry = QtGui.QLineEdit(self.tab_3)
        self.symbolEntry.setGeometry(QtCore.QRect(10, 20, 221, 29))
        self.symbolEntry.setObjectName("symbolEntry")
        self.loadSymbol = QtGui.QPushButton(self.tab_3)
        self.loadSymbol.setGeometry(QtCore.QRect(10, 60, 110, 29))
        self.loadSymbol.setObjectName("loadSymbol")
        self.addSymbol = QtGui.QPushButton(self.tab_3)
        self.addSymbol.setGeometry(QtCore.QRect(120, 60, 110, 29))
        self.addSymbol.setObjectName("addSymbol")
        self.newTab = QtGui.QPushButton(self.tab_3)
        self.newTab.setGeometry(QtCore.QRect(60, 90, 110, 29))
        self.newTab.setObjectName("newTab")
        self.tabWidget.addTab(self.tab_3, "")
        self.nextDay = QtGui.QPushButton(chartWidget)
        self.nextDay.setGeometry(QtCore.QRect(850, 930, 110, 29))
        self.nextDay.setObjectName("nextDay")
        self.next30 = QtGui.QPushButton(chartWidget)
        self.next30.setGeometry(QtCore.QRect(960, 930, 110, 29))
        self.next30.setObjectName("next30")
        self.prev30 = QtGui.QPushButton(chartWidget)
        self.prev30.setGeometry(QtCore.QRect(960, 980, 110, 29))
        self.prev30.setObjectName("prev30")
        self.prevDay = QtGui.QPushButton(chartWidget)
        self.prevDay.setGeometry(QtCore.QRect(850, 980, 110, 29))
        self.prevDay.setObjectName("prevDay")
        self.chartTabs = QtGui.QTabWidget(chartWidget)
        self.chartTabs.setGeometry(QtCore.QRect(0, 0, 1071, 871))
        self.chartTabs.setObjectName("chartTabs")
        self.firstChart = QtGui.QWidget()
        self.firstChart.setObjectName("firstChart")
        self.horizontalLayoutWidget = QtGui.QWidget(self.firstChart)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-10, -10, 1081, 851))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chart = QtGui.QGraphicsView(self.horizontalLayoutWidget)
        self.chart.setObjectName("chart")
        self.horizontalLayout.addWidget(self.chart)
        self.chartTabs.addTab(self.firstChart, "")

        self.retranslateUi(chartWidget)
        self.tabWidget.setCurrentIndex(2)
        self.chartTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(chartWidget)

    def retranslateUi(self, chartWidget):
        chartWidget.setWindowTitle(QtGui.QApplication.translate("chartWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomIn.setText(QtGui.QApplication.translate("chartWidget", "Zoom In", None, QtGui.QApplication.UnicodeUTF8))
        self.zoomOut.setText(QtGui.QApplication.translate("chartWidget", "Zoom Out", None, QtGui.QApplication.UnicodeUTF8))
        self.sma.setText(QtGui.QApplication.translate("chartWidget", "sma", None, QtGui.QApplication.UnicodeUTF8))
        self.chartLength.setText(QtGui.QApplication.translate("chartWidget", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.candlestick.setText(QtGui.QApplication.translate("chartWidget", "Candlestick", None, QtGui.QApplication.UnicodeUTF8))
        self.ohlc.setText(QtGui.QApplication.translate("chartWidget", "OHLC", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("chartWidget", "Chart Style", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("chartWidget", "Technical Indicators:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.chartControls), QtGui.QApplication.translate("chartWidget", "Chart Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.buy.setText(QtGui.QApplication.translate("chartWidget", "Buy", None, QtGui.QApplication.UnicodeUTF8))
        self.sell.setText(QtGui.QApplication.translate("chartWidget", "Sell", None, QtGui.QApplication.UnicodeUTF8))
        self.showBalance.setText(QtGui.QApplication.translate("chartWidget", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.balanceLabel.setText(QtGui.QApplication.translate("chartWidget", "Balance:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.account), QtGui.QApplication.translate("chartWidget", "Account", None, QtGui.QApplication.UnicodeUTF8))
        self.loadSymbol.setText(QtGui.QApplication.translate("chartWidget", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.addSymbol.setText(QtGui.QApplication.translate("chartWidget", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.newTab.setText(QtGui.QApplication.translate("chartWidget", "New Tab", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("chartWidget", "Watchlist", None, QtGui.QApplication.UnicodeUTF8))
        self.nextDay.setText(QtGui.QApplication.translate("chartWidget", "Next Day", None, QtGui.QApplication.UnicodeUTF8))
        self.next30.setText(QtGui.QApplication.translate("chartWidget", "Next 30", None, QtGui.QApplication.UnicodeUTF8))
        self.prev30.setText(QtGui.QApplication.translate("chartWidget", "Prev 30", None, QtGui.QApplication.UnicodeUTF8))
        self.prevDay.setText(QtGui.QApplication.translate("chartWidget", "Prev Day", None, QtGui.QApplication.UnicodeUTF8))
        self.chartTabs.setTabText(self.chartTabs.indexOf(self.firstChart), QtGui.QApplication.translate("chartWidget", "MSFT", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    chartWidget = QtGui.QWidget()
    ui = Ui_chartWidget()
    ui.setupUi(chartWidget)
    chartWidget.show()
    sys.exit(app.exec_())

